In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [ ]:
array = np.array(my_list)
print(array)

[1 2 3 4 5 6]


In [ ]:
print(array.ndim)
print(array.shape)
print(len(array))
print(type(array))

1
(6,)
6
<class 'numpy.ndarray'>


In [ ]:
array2= array.reshape(2,3)
print(array2)

[[1 2 3]
 [4 5 6]]


In [ ]:
array3= array.reshape(1,2,-1)
print(array3)

[[[1 2 3]
  [4 5 6]]]


In [ ]:
x = array.reshape(3,2)
print(x.base)

[1 2 3 4 5 6]


In [ ]:
array4= array3.reshape(-1)
print(array4)

[1 2 3 4 5 6]


In [ ]:
a= np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
b = a.reshape(2,6,-1)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [ ]:
x = np.array([[1,2],[5,6]], dtype= np.float64)
y = np.array([[3,4],[7,8]], dtype= np.float64)
print(x)
print(y)


[[1. 2.]
 [5. 6.]]
[[3. 4.]
 [7. 8.]]


In [ ]:
print(x + y)
print(np.add(x,y))

[[ 4.  6.]
 [12. 14.]]
[[ 4.  6.]
 [12. 14.]]


In [ ]:
print(np.power(x,y))

[[1.000000e+00 1.600000e+01]
 [7.812500e+04 1.679616e+06]]


In [ ]:
x = np.array([[1,2],[5,6]])
y = np.array([[3,4],[7,8]])
print(x)
print(y)

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [ ]:
print(np.power(x,y))

[[      1      16]
 [  78125 1679616]]


In [ ]:
print(np.sum(x, axis =1))

[ 3 11]


**Pandas for Data Science**

In [ ]:
import pandas as pd
import io

In [ ]:
from google.colab import files


uploaded = files.upload()

Saving IRIS.csv to IRIS.csv


In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['IRIS.csv']))
print(df)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
df= pd.read_csv(io.BytesIO(uploaded['IRIS.csv']), index_col=0)  #Treating first column as index 

print(df)

              sepal_width  petal_length  petal_width         species
sepal_length                                                        
5.1                   3.5           1.4          0.2     Iris-setosa
4.9                   3.0           1.4          0.2     Iris-setosa
4.7                   3.2           1.3          0.2     Iris-setosa
4.6                   3.1           1.5          0.2     Iris-setosa
5.0                   3.6           1.4          0.2     Iris-setosa
...                   ...           ...          ...             ...
6.7                   3.0           5.2          2.3  Iris-virginica
6.3                   2.5           5.0          1.9  Iris-virginica
6.5                   3.0           5.2          2.0  Iris-virginica
6.2                   3.4           5.4          2.3  Iris-virginica
5.9                   3.0           5.1          1.8  Iris-virginica

[150 rows x 4 columns]


In [ ]:
df= pd.read_csv(io.BytesIO(uploaded['IRIS.csv']), index_col=False, na_values=['??'])
print(df)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
print(df.to_string)

<bound method DataFrame.to_string of      sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>


In [ ]:
# Creates a new variable that shares a reference of original object
# Any changes made to a copy of object will reflect in original object also
shallow_copy = df.copy(deep=False)
shallow_copy

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# Creates a new variable that shares a no reference of original object
# copy of object is copied in other object
# Any changes made to a copy of object will not reflect in original object
deep_copy = df.copy(deep=True)
deep_copy

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
deep_copy.index

RangeIndex(start=0, stop=150, step=1)

In [ ]:
df.index # return the index of all dataset

RangeIndex(start=0, stop=150, step=1)

In [ ]:
df.loc[5] #return specified number of row
#this return the row in form of pandas series

sepal_length            5.4
sepal_width             3.9
petal_length            1.7
petal_width             0.4
species         Iris-setosa
Name: 5, dtype: object

In [ ]:
df.loc[[2,3,4]] #return specified number of row
#when use [], return the row in form of pandas dataframe

sepal_length  sepal_width  petal_length  petal_width      species
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df.loc[:,'sepal_length']

# Dataframe.[ ] ; This function also known as indexing operator
# Dataframe.loc[ ] : This function is used for labels.
# Dataframe.iloc[ ] : This function is used for positions or integer based
# Dataframe.ix[] : This function is used for both label and integer based

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
df.iloc[:, 2]

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [ ]:
df.columns #total colums name in form of list

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
df["sepal_length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
df.species

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [ ]:
first = df[["sepal_length", "sepal_width"]]  #retriving multiple column by indexing operator.
first

sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [ ]:
df.size #total number of elements

750

In [ ]:
df.shape #total number of rows and columns

(150, 5)

In [ ]:
 df.memory_usage()
 #Gives memory use by each column in bytes

Index            128
sepal_length    1200
sepal_width     1200
petal_length    1200
petal_width     1200
species         1200
dtype: int64

In [ ]:
df.ndim #dimension of dataframe

2

In [ ]:
df.head(6) #First n rows from dataset

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa

In [ ]:
df.tail(5) #last n rows in dataset

sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
df.at[4,'petal_length'] 
#at provide label-based lookups(used to access a scalarvalue this is a fastest way)
#to access a scalar value pass paramter row and column name in the at attribute

1.4

In [ ]:
df.iat[4,2]
#iat provide integer-based lookups
#to access a scalar value pass paramter row and column index in the iat attribute

In [ ]:
# In datatype memory allocated to store data in each cell is also specified.
# INT64 means 64 bits space is available to store integer data.
# Allocating space ahead of time allows computer to optimize storage and
#  processing efficiency.

df.dtypes 

# Object dtype = column will assigned as object datatype when it has mixed
#  types(number and string). column containing nan(blank cell) will default to
#  object datatype.

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [ ]:
df.dtypes.value_counts() #Return a unique datatype in dataframe

float64    4
object     1
dtype: int64

In [ ]:
 # df.get_dtype_counts() DataFrame' object has no attribute 'get_dtype_counts'

In [ ]:
df.select_dtypes(include = None,  exclude = [object]) 
# return subset of columns from dataframe based on columns dtypes

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
df.select_dtypes(include = ['float64', 'object'], exclude = None) 


sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.select_dtypes(include = [object]) 

In [ ]:
df.info() #give concise summary of dataframe

#gives info about total no. of rows and columns in dataframe, no. of dtypes, 
#   column name and non-null count in that particular column.


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
np.unique(df['petal_width']) #return distinct values from given column

#only one column name can be passed as parameter

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
       1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5])

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Iris1.csv to Iris1 (1).csv


In [ ]:
df1 = pd.read_csv(io.BytesIO(uploaded['Iris1.csv']))
print(df1)

     sepal_length sepal_width  petal_length  petal_width         species
0             5.1         3.5           1.4          0.2     Iris-setosa
1             4.9           3           1.4          0.2     Iris-setosa
2             4.7         3.2           1.3          0.2     Iris-setosa
3             4.6         3.1           1.5          0.2     Iris-setosa
4             5.0         3.6           1.4          0.2     Iris-setosa
..            ...         ...           ...          ...             ...
145           6.7           3           5.0          2.3  Iris-virginica
146           6.3         2.5           5.0          1.9  Iris-virginica
147           6.5           3           5.2          2.0  Iris-virginica
148           6.2         3.4           5.4          2.3  Iris-virginica
149           5.9           3           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    object 
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(3), object(2)
memory usage: 6.0+ KB


In [ ]:
np.unique(df1['sepal_width'])

array(['2', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '2.8', '2.9', '3',
       '3.1', '3.2', '3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '4',
       '4.1', '4.2', '4.4', '???'], dtype=object)

In [ ]:
np.unique(df1['petal_length'])

array([1, 3, 4, 5, 6])

In [ ]:
np.unique(df1['petal_width'])

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
       1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5])

In [ ]:
from pandas.core.reshape.tile import is_numeric_dtype
is_numeric_dtype(df1['petal_length']) 

True

In [ ]:
df1 = pd.read_csv(io.BytesIO(uploaded['Iris1.csv']), index_col = False, na_values= ['???'])
print(df1)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.0          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   148 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df1['petal_length'] = df1['petal_length'].astype('float64')
print(df1)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.0          0.2     Iris-setosa
1             4.9          3.0           1.0          0.2     Iris-setosa
2             4.7          3.2           1.0          0.2     Iris-setosa
3             4.6          3.1           1.0          0.2     Iris-setosa
4             5.0          3.6           1.0          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.0          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.0          2.0  Iris-virginica
148           6.2          3.4           5.0          2.3  Iris-virginica
149           5.9          3.0           5.0          1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
np.unique(df1['petal_length'])

array([1., 3., 4., 5., 6.])

In [ ]:
df1['petal_length'] = df1['petal_length'].astype('int64')
print(df1)

# astype use to explicitly convert data types from one to another

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5             1          0.2     Iris-setosa
1             4.9          3.0             1          0.2     Iris-setosa
2             4.7          3.2             1          0.2     Iris-setosa
3             4.6          3.1             1          0.2     Iris-setosa
4             5.0          3.6             1          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0             5          2.3  Iris-virginica
146           6.3          2.5             5          1.9  Iris-virginica
147           6.5          3.0             5          2.0  Iris-virginica
148           6.2          3.4             5          2.3  Iris-virginica
149           5.9          3.0             5          1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   148 non-null    float64
 2   petal_length  150 non-null    int64  
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(3), int64(1), object(1)
memory usage: 6.0+ KB


In [ ]:
# nbytes used to get total bytes consumed by elements of columns

df1['species'].nbytes #total bytes consumed when datatype is object

1200

In [ ]:
df1['species'].astype('category').nbytes 

#total bytes consumed when datatype is category

174

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving IRIS2.csv to IRIS2.csv


In [ ]:
df2 = pd.read_csv(io.BytesIO(uploaded['IRIS2.csv']))
print(df2)

     sepal_length  sepal_width petal_length  petal_width         species
0             5.1          3.5          1.4          0.2     Iris-setosa
1             4.9          3.0          1.4          0.2     Iris-setosa
2             4.7          3.2          1.3          0.2     Iris-setosa
3             4.6          3.1          1.5          0.2     Iris-setosa
4             5.0          3.6          1.4          0.2     Iris-setosa
..            ...          ...          ...          ...             ...
145           6.7          3.0          5.2          2.3  Iris-virginica
146           6.3          2.5            5          1.9  Iris-virginica
147           6.5          3.0          5.2          2.0  Iris-virginica
148           6.2          3.4          5.4          2.3  Iris-virginica
149           5.9          3.0          5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    object 
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(3), object(2)
memory usage: 6.0+ KB


In [ ]:
df2.tail(15)

sepal_length  sepal_width    petal_length  petal_width         species
135           7.7          3.0             6.1          2.3  Iris-virginica
136           6.3          3.4             5.6          2.4  Iris-virginica
137           6.4          3.1             5.5          1.8  Iris-virginica
138           6.0          3.0             4.8          1.8  Iris-virginica
139           6.9          3.1            five          2.1  Iris-virginica
140           6.7          3.1             5.6          2.4  Iris-virginica
141           6.9          3.1             5.1          2.3  Iris-virginica
142           5.8          2.7             5.1          1.9  Iris-virginica
143           6.8          3.2             5.9          2.3  Iris-virginica
144           6.7          3.3  five point two          2.5  Iris-virginica
145           6.7          3.0             5.2          2.3  Iris-virginica
146           6.3          2.5               5          1.9  Iris-virginica
147           6.5          3.0             5.2          2.0  Iris-virginica
148           6.2          3.4             5.4          2.3  Iris-virginica
149           5.9          3.0             5.1          1.8  Iris-virginica

In [ ]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [ ]:
df2['petal_length'].replace('five', 5.0, inplace= True)
df2['petal_length'].replace('five point two', 5.2, inplace= True)

print(df2)

#Replace a value with desired value

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
df2.tail(12)

sepal_length  sepal_width petal_length  petal_width         species
138           6.0          3.0          4.8          1.8  Iris-virginica
139           6.9          3.1          5.0          2.1  Iris-virginica
140           6.7          3.1          5.6          2.4  Iris-virginica
141           6.9          3.1          5.1          2.3  Iris-virginica
142           5.8          2.7          5.1          1.9  Iris-virginica
143           6.8          3.2          5.9          2.3  Iris-virginica
144           6.7          3.3          5.2          2.5  Iris-virginica
145           6.7          3.0          5.2          2.3  Iris-virginica
146           6.3          2.5            5          1.9  Iris-virginica
147           6.5          3.0          5.2          2.0  Iris-virginica
148           6.2          3.4          5.4          2.3  Iris-virginica
149           5.9          3.0          5.1          1.8  Iris-virginica

In [ ]:
df2['petal_length'] = df2['petal_length'].astype('float64')
print(df2)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
np.unique(df2["petal_length"])

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.9, 3. , 3.3, 3.5, 3.6,
       3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9,
       5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.3,
       6.4, 6.6, 6.7, 6.9])

In [ ]:
df.isnull().sum()  #detect missing values

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df['sepal_length'].value_counts().index[0]

# Returns a Series containing counts of unique values.The values will be in desc order so that the 1st element is the most frequently-occurring element.
# Excludes NA values by default

5.0