In [1]:
my_str = 'Shreya Satpute'

In [2]:
my_str.isspace()

False

In [3]:
my_str.isalnum()

False

In [4]:
my_str.isalpha()

False

In [5]:
my_str.istitle()

True

In [6]:
my_str2 = 'ShreyaSatpute'

In [7]:
my_str2.istitle()

False

In [8]:
my_str2.isalpha()

True

In [9]:
my_str3 = 'ShreyaSatpute2'

In [10]:
my_str3.istitle()

False

In [11]:
my_str3.isalnum()

True

In [12]:
my_str1 = 'Shreya Satpute12'

In [13]:
my_str1.isspace()

False

In [14]:
my_str1.isalpha()

False

In [15]:
my_str1.isdigit()

False

In [16]:
my_str1.isalnum()

False

### List


In [17]:
lst = list()

In [18]:
type(lst)

list

In [19]:
lst = ['Math', 'CS',1,2,3,4,]

In [20]:
len(lst)

6

In [21]:
# Append is to add element in the list at the end

lst.append('Bunty')

In [22]:
lst

['Math', 'CS', 1, 2, 3, 4, 'Bunty']

In [23]:
# indexing

lst[6]

'Bunty'

In [24]:
lst[ :5]

['Math', 'CS', 1, 2, 3]

In [25]:
lst[3:]

[2, 3, 4, 'Bunty']

In [26]:
# Insert used to add element in specific order

lst.insert(2,'Analytic')

In [27]:
lst

['Math', 'CS', 'Analytic', 1, 2, 3, 4, 'Bunty']

In [28]:
lst.append(['Hello World'])

In [29]:
lst

['Math', 'CS', 'Analytic', 1, 2, 3, 4, 'Bunty', ['Hello World']]

In [30]:
lst = [2,3,4]

In [31]:
lst

[2, 3, 4]

In [32]:
lst.extend([5,6])

In [33]:
lst

[2, 3, 4, 5, 6]

In [34]:
lst.append([7,8])

In [35]:
lst

[2, 3, 4, 5, 6, [7, 8]]

In [36]:
lst.pop() 

# by default remove last element

[7, 8]

In [37]:
lst

[2, 3, 4, 5, 6]

In [38]:
sum(lst)

20

In [39]:
lst*2

# append whole list 2 times

[2, 3, 4, 5, 6, 2, 3, 4, 5, 6]

In [40]:
lst = [1,1,1,1,2,3,4]

In [41]:
lst.count(1)

4

In [42]:
lst.index(1,2,5)

# returns the index of first occurance.
# Start and End index are not necessary parameters

2

In [43]:
lst.index(2,2,5)

4

In [44]:
lst.index(1,0,4)

0

### Sets

Set is unordered collection of data type that is iterable, mutable, and has no duplicates. It is Based on data structure known as hash table.

In [45]:
# Defining an empty set

set_var = set()
print(set_var)


set()


In [46]:
print(type(set_var))

<class 'set'>


In [47]:
set_var = {1,2,3,4,5} 
print(set_var)

{1, 2, 3, 4, 5}


In [48]:
set1 = {'Avengers','Ironman','Hitman'}
print(set1)

{'Avengers', 'Ironman', 'Hitman'}


In [50]:
# dose not support indexing

set_var[0]

TypeError: 'set' object is not subscriptable

In [51]:
set1['Avengers']

TypeError: 'set' object is not subscriptable

In [52]:
# Inbuilt function in sets
set1.add('Hulk')

In [53]:
print(set1)

{'Avengers', 'Hulk', 'Ironman', 'Hitman'}


In [54]:
set2 = {'Avengers','Ironman','Hitman','Hulk2'}


In [55]:
set2.intersection(set1)

{'Avengers', 'Hitman', 'Ironman'}

In [56]:
set2.intersection_update(set1)

In [57]:
set2

{'Avengers', 'Hitman', 'Ironman'}

In [58]:
set2.difference(set1)

# difference function dose not update the final output in set2

set()

In [59]:
# to update difference use function difference_update

set2.difference_update(set1)

In [60]:
set2

set()

### Dictionaries

Dictionasy is unordered collection which is mutable and indexed. It has key-value pair.

In [61]:
dic={}

In [62]:
type(dic)

dict

In [63]:
dic = {1,2,3,4,5}

In [64]:
type(dic)

set

In [65]:
dict = {"a":1,"b":2,"c":3}

In [66]:
type(dict)

dict

In [67]:
print(dict)

{'a': 1, 'b': 2, 'c': 3}


In [68]:

# indexing is ur key name
# access the item values based on keys

dict['a']

1

In [69]:
# looping through the dictonary values

for x in dict:
    print(x)

a
b
c


In [70]:
for x in dict.values():
    print(x)

1
2
3


In [71]:
# check both keys and values

for x in dict.items():
    print(x)

('a', 1)
('b', 2)
('c', 3)


In [72]:
# adding item in dict

dict['d']=4

In [73]:
dict

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [74]:
# values got overwritten

dict['b']=8

In [75]:
dict

{'a': 1, 'b': 8, 'c': 3, 'd': 4}

In [76]:
# NESTED DICT

dict1= {1:'first'}
dict2 = {2:'Second'}
dict3 = {3:'Third'}
dict4 = {4:'Fourth'}

new_dict = {"a":dict1, 'b':dict2, 'c':dict3, 'd':dict4}

In [77]:
print(new_dict)

{'a': {1: 'first'}, 'b': {2: 'Second'}, 'c': {3: 'Third'}, 'd': {4: 'Fourth'}}


In [78]:
print(new_dict['b'])

{2: 'Second'}


In [79]:
print(new_dict['b'][2])

Second


### Tuples

Tuples are immutable 

In [80]:
my_tup = tuple()

In [81]:
type(my_tup)

tuple

In [82]:
my_tup = ()

In [83]:
type(my_tup)

tuple

In [84]:
tup = ('shre', 'oja')

In [85]:
print(tup)

('shre', 'oja')


In [86]:
tup[0]

'shre'

In [87]:
tup[0]='sam'

# dose not support item assignment

TypeError: 'tuple' object does not support item assignment

In [88]:
tup.index('oja')

1

### Numpy

General purpose array processing package. Create multidimensional array, 
provides high performance multidimensional array object, and tools for working with these array. Numpy has binding of cpp library therefore operatin take place fast.

Array data structure that stores values of same data type. Array operation are very very fast. 

In [89]:
import numpy as np

In [90]:
my_lst = [1,2,3,4,5]

In [91]:
arr = np.array(my_lst)

In [92]:
arr #1D array

array([1, 2, 3, 4, 5])

In [93]:
print(arr)

[1 2 3 4 5]


In [94]:
type(arr)

numpy.ndarray

In [95]:
arr.shape

(5,)

In [96]:
# Multinested array

my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,8,7,6,5]

arr = np.array([my_lst1, my_lst2, my_lst3])


In [97]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [98]:
arr.shape

(3, 5)

In [99]:
arr.reshape(5,3)

# Total array element should remain same

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 8],
       [7, 6, 5]])

In [100]:
arr.shape

(3, 5)

In [101]:
arr.size

15

In [102]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 8, 7, 6, 5]])

In [103]:
# indexing

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [104]:
arr[1:, 3:]

array([[5, 6],
       [6, 5]])

In [105]:
arr=np.arange(0,10)

In [106]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr = np.arange(0,10,step=2)

In [108]:
arr

array([0, 2, 4, 6, 8])

In [109]:
np.linspace(1,10,20) # how many points u want in given start and end point

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [110]:
arr = [1,2,3,4,5,6,7,8,9]
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [111]:
arr[4]=100

In [112]:
arr[3:]=100

TypeError: can only assign an iterable

In [113]:
### Some conditions very useful in Exploratory Data Analysis 

val=2

arr[arr<3]

TypeError: '<' not supported between instances of 'list' and 'int'

In [114]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [115]:
arr1=np.arange(0,10).reshape(2,5)

In [116]:
arr2=np.arange(0,10).reshape(2,5)

In [117]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [118]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [119]:
## random distribution
np.random.rand(3,3)

array([[0.73901874, 0.04341629, 0.36514236],
       [0.41547301, 0.40015495, 0.37522976],
       [0.06831679, 0.89698464, 0.61157335]])

In [120]:
arr_ex=np.random.randn(4,4)

In [121]:
arr_ex

array([[ 2.49416577, -0.66002597, -1.53311836,  1.38367177],
       [ 1.76890181,  1.19548279,  0.05137301, -0.42772285],
       [ 1.10812216, -0.57993447,  2.01917022, -0.41592024],
       [-0.4579003 , -2.11734264,  0.84195717, -0.24659669]])

In [122]:
np.random.randint(0,100,8).reshape(4,2)

array([[56, 97],
       [ 5, 18],
       [20, 33],
       [72,  5]])

In [123]:
np.random.random_sample((1,5))

array([[0.72963021, 0.29780434, 0.66091544, 0.38754094, 0.9714446 ]])